name: Trivy Security Scan

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: read
  actions: read
  pull-requests: write

env:
  TRIVY_CACHE_DIR: /tmp/trivy-cache

jobs:
  trivy-scan:
    name: Full Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Cache Trivy DB
        uses: actions/cache@v5
        with:
          path: ${{ env.TRIVY_CACHE_DIR }}
          key: trivy-db-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            trivy-db-${{ runner.os }}-

      - name: Run Trivy Scan (Vuln, Secret, Misconfig, License)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          trivy-config: trivy.yaml
          format: json
          output: trivy-results.json

      - name: Extract Trivy summary
        id: summary
        run: |
            DATA='[
              .Results[].Vulnerabilities[]?,
              .Results[].Misconfigurations[]?,
              .Results[].Secrets[]?,
              .Results[].Licenses[]?
            ]'

            CRITICAL=$(jq "$DATA | map(select(.Severity==\"CRITICAL\")) | length" trivy-results.json)
            HIGH=$(jq "$DATA | map(select(.Severity==\"HIGH\")) | length" trivy-results.json)
    

            TOP_ISSUES=$(jq -r "$DATA
            | map(select(.Severity==\"CRITICAL\" or .Severity==\"HIGH\"))
            | map(\"- **ID:** \(.ID // .VulnerabilityID // \"N/A\")\n  **Title:** \(.Title // .PkgName // .Message // \"N/A\")\n  **Description:** \(((.Description // .Message // \"N/A\") | gsub(\"\\n\"; \" \") | .[:150]))\n  **Link:** \(.PrimaryURL // \"N/A\")\")
            | join(\"\\n\\n\")
            " trivy-results.json)


            RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

            echo "critical=$CRITICAL" >> $GITHUB_OUTPUT
            echo "high=$HIGH" >> $GITHUB_OUTPUT
            echo "run_url=$RUN_URL" >> $GITHUB_OUTPUT

            echo "issues<<EOF" >> $GITHUB_OUTPUT
            echo "$TOP_ISSUES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT

      # - name: Comment PR with Trivy summary
      #   uses: marocchino/sticky-pull-request-comment@v3
      #   with:
      #     header: trivy-scan
      #     message: |
      #       **Trivy Security Scan Result**

      #       **Critical:** ${{ steps.summary.outputs.critical }}
      #       **High:** ${{ steps.summary.outputs.high }}

      #       **Top Issues Found**
      #       ${{ steps.summary.outputs.issues }}

      #       High / Critical security issues detected. Please resolve them before merging this PR.

      #       **Full report:** [Open workflow run](${{ steps.summary.outputs.run_url }})
      #       _Download the full trivy-report from the workflow run page._


      - name: Comment PR with Trivy summary
        uses: actions/github-script@v9
        with:
          script: |
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `
              **Trivy Security Scan Result**

              **Critical:** ${{ steps.summary.outputs.critical }}
              **High:** ${{ steps.summary.outputs.high }}

              ${{ steps.summary.outputs.issues }}

              Full report: ${{ steps.summary.outputs.run_url }}`
            });

      - name: Upload Trivy report
        uses: actions/upload-artifact@v7
        with:
          name: trivy-report
          path: trivy-results.json

      - name: Fail if vulnerabilities found
        run: |
            if [ "${{ steps.summary.outputs.critical }}" -gt 0 ] || [ "${{ steps.summary.outputs.high }}" -gt 0 ]; then
              echo "Failing due to HIGH/CRITICAL security issues"
              exit 1
            fi

      # - name: Upload Trivy SARIF to GitHub Security
      #   if: always()
      #   uses: github/codeql-action/upload-sarif@v4
      #   with:
      #     sarif_file: trivy-results.sarif
      #     category: trivy-iac
